### ISSUE TITLE
Integrate with MTEB?

### ISSUE THREAD

**Issue by Muennighoff** [CoIR-team/coir#4]
Amazing work! It'd be great to have the benchmark integrated in MTEB (https://github.com/embeddings-benchmark/mteb) if you're interested :) I think it'd be great for the community & visibility of your project 😊 Should be pretty simple given your format - We'd just need a PR like one of these: [LongEmbed](https://github.com/embeddings-benchmark/mteb/pull/393) ; [Law](https://github.com/embeddings-benchmark/mteb/pull/311) ; [FollowIR](https://github.com/embeddings-benchmark/mteb/pull/408) ; [French](https://github.com/embeddings-benchmark/mteb/pull/218) ; [Scandinavian](https://github.com/embeddings-benchmark/mteb/pull/124) 🙌

**Comment by archersama** [comment]
Thanks for your attention and support. We will endeavor to integrate COIR into MTEB in the near future.
